name: Run main.py on self-hosted runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Pull latest into githubActions2/githubActions
        shell: cmd
        working-directory: C:\Users\asus\Desktop\postgresql\githubActions2\githubActions
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Run main.py
        shell: cmd
        working-directory: C:\Users\asus\Desktop\postgresql\githubActions2\githubActions
        run: python main.py
