name: Run main.py on self-hosted runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run main.py
        shell: cmd
        run: python main.py
